// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhOkssSNZLcNGPro8Ml1p2HhuBuea_VNA',
    appId: '1:25354252153:web:5532a1c63b13d76b5549a8',
    messagingSenderId: '25354252153',
    projectId: 'shop-app-8bfdb',
    authDomain: 'shop-app-8bfdb.firebaseapp.com',
    storageBucket: 'shop-app-8bfdb.firebasestorage.app',
    measurementId: 'G-EH5SFTM7JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR50fJB-JUXgUoJtwHdnHm3cmCeg8pjxE',
    appId: '1:25354252153:android:2eff08bb9ab646d75549a8',
    messagingSenderId: '25354252153',
    projectId: 'shop-app-8bfdb',
    storageBucket: 'shop-app-8bfdb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXPJJoz0nTa5z4FCwbsNgQWIy0iqkzGyE',
    appId: '1:25354252153:ios:1f6758faf0d4c8ad5549a8',
    messagingSenderId: '25354252153',
    projectId: 'shop-app-8bfdb',
    storageBucket: 'shop-app-8bfdb.firebasestorage.app',
    iosBundleId: 'com.example.exercise8525',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXPJJoz0nTa5z4FCwbsNgQWIy0iqkzGyE',
    appId: '1:25354252153:ios:1f6758faf0d4c8ad5549a8',
    messagingSenderId: '25354252153',
    projectId: 'shop-app-8bfdb',
    storageBucket: 'shop-app-8bfdb.firebasestorage.app',
    iosBundleId: 'com.example.exercise8525',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhOkssSNZLcNGPro8Ml1p2HhuBuea_VNA',
    appId: '1:25354252153:web:ee7c68592afee0dc5549a8',
    messagingSenderId: '25354252153',
    projectId: 'shop-app-8bfdb',
    authDomain: 'shop-app-8bfdb.firebaseapp.com',
    storageBucket: 'shop-app-8bfdb.firebasestorage.app',
    measurementId: 'G-14VQVYDRJE',
  );
}
